version: "3.8"

services:
  db:
    image: postgres:15.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./.docker/postgres_data:/var/lib/postgresql/data
